project:
  type: website
  preview:
    port: 9999
  resources:
    - /assets

website:
  title: "Denis E. Sergeev"
  favicon: /assets/favicon.ico
  description: "Denis E. Sergeev's academic website"
  navbar:
    right:
      - about.qmd
      - publications.qmd
    alignment: center

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: false
    crossrefs-hover: true
